server:
  port: 8081


# 配置OpenAI
spring:
  application:
    name: prescription-service
  datasource:
    url: jdbc:mysql://47.94.245.245:3306/AIHospital?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 60.205.113.149:8848
  ai:
    openai:
      api-key: sk-d1022725fada4052825318244e6ca73b
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8


logging:
  level:
    root: error
    org.springframework.ai.chat.client: DEBUG

